version: '3.9'
services:
  db:
    image: postgres:16
    container_name: veterinaria_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: veterinaria
    volumes:
      - pgdata_vet:/var/lib/postgresql/data
volumes:
  pgdata_vet:


